In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(3, 2, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a NumPy Array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Array

In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int32')

In [17]:
ones = np.ones((2,3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2,3))

In [22]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [27]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[5, 9, 0, 1, 1],
       [7, 0, 9, 9, 7],
       [5, 2, 6, 8, 6]])

In [28]:
random_array.size

15

In [29]:
random_array.shape

(3, 5)

In [30]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.1407462 , 0.14314619, 0.24827481],
       [0.72349739, 0.90884784, 0.4757002 ],
       [0.63886739, 0.36016867, 0.92705742],
       [0.39277454, 0.17983625, 0.47678376],
       [0.53083252, 0.83723095, 0.53919546]])

In [31]:
random_array_2.shape

(5, 3)

In [32]:
random_array_3 = np.random.rand(5,3)
random_array_3 

array([[0.65092445, 0.45031406, 0.76758593],
       [0.03819576, 0.33819283, 0.80524858],
       [0.62618424, 0.49331261, 0.90115789],
       [0.56048922, 0.98515956, 0.1240752 ],
       [0.76351797, 0.93133849, 0.47208343]])

In [42]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [43]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.79172504, 0.52889492, 0.56804456],
       [0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675],
       [0.87001215, 0.97861834, 0.79915856],
       [0.46147936, 0.78052918, 0.11827443]])

In [45]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.3595079 , 0.43703195, 0.6976312 ],
       [0.06022547, 0.66676672, 0.67063787],
       [0.21038256, 0.1289263 , 0.31542835],
       [0.36371077, 0.57019677, 0.43860151],
       [0.98837384, 0.10204481, 0.20887676]])

In [34]:
random_array_4.shape

(5, 3)

In [ ]:
## 3. Viewing arrays & numbers